-- 0017_source_inventory_p0_seed.sql
--
-- Seed the first reviewed P0 batch from the July 2026 government API inventory into
-- the private source catalog created by 0016. These rows are review candidates only;
-- they do not add extractors, public facts, or scraper dependencies.

SET statement_timeout = '30s';

INSERT INTO public.source_catalog_sources (
    slug,
    name,
    agency,
    sub_agency,
    branch,
    category,
    source_type,
    access_level,
    auth_type,
    credential_provider,
    base_url,
    docs_url,
    formats,
    coverage,
    update_cadence,
    priority,
    status,
    verified_lane,
    repo_fit,
    verified_at,
    notes,
    metadata
) VALUES
    (
        'api-data-gov',
        'api.data.gov API management service / key platform',
        'General Services Administration',
        'TTS / Data.gov',
        'executive',
        'source_discovery',
        'directory',
        'open',
        'api_key',
        'api.data.gov',
        'https://api.data.gov/',
        'https://api.data.gov/',
        ARRAY['varies']::text[],
        'Federal agency APIs using api.data.gov; official key and rate-limit management.',
        'continuous',
        'P0',
        'candidate',
        'not_applicable',
        'needs_review',
        DATE '2026-07-03',
        'Credential and registry backbone for official sources; currently used indirectly by the FEC key path.',
        jsonb_build_object(
            'inventory_file', 'us_government_api_seed_inventory_repo_status',
            'inventory_status', 'Verified public docs',
            'repo_usage_status', 'Already used indirectly as key/gateway',
            'repo_evidence', 'scraper/example.env defines FEC_API_KEY as an api.data.gov key; scraper/main.py gates FEC donor enrichment on FEC_API_KEY.',
            'repo_next_action', 'Keep as credential_provider/gateway. Do not count it as a standalone data source unless modeling API management separately.',
            'source_url', 'https://api.data.gov/'
        )
    ),
    (
        'datagov-catalog-api-v4',
        'Data.gov Catalog API v4',
        'General Services Administration',
        'Data.gov',
        'executive',
        'source_discovery',
        'api',
        'free_key',
        'api_key',
        'api.data.gov',
        'https://api.gsa.gov/technology/datagov/v4/',
        'https://resources.data.gov/catalog-api/',
        ARRAY['json']::text[],
        'Metadata for datasets published by federal, state, local, and tribal governments.',
        'harvested / ongoing',
        'P0',
        'candidate',
        'not_applicable',
        'needs_review',
        DATE '2026-07-03',
        'Primary source-discovery crawler candidate; useful for finding API distributions before adding extractors.',
        jsonb_build_object(
            'inventory_file', 'us_government_api_seed_inventory_repo_status',
            'inventory_status', 'Verified public docs',
            'repo_usage_status', 'New candidate / not currently wired',
            'repo_next_action', 'Evaluate for fit, auth, quota, schema, and official-source provenance before adding an extractor.',
            'source_url', 'https://resources.data.gov/catalog-api/'
        )
    ),
    (
        'datagov-harvester-api',
        'Data.gov Harvester API',
        'General Services Administration',
        'Data.gov',
        'executive',
        'source_discovery',
        'api',
        'free_key',
        'api_key',
        'api.data.gov / open.gsa.gov',
        'https://api.gsa.gov/technology/datagov_harvest/v2/',
        'https://resources.data.gov/harvester-api/',
        ARRAY['json', 'openapi']::text[],
        'Harvest sources, jobs, harvest records, and errors for Data.gov publisher feeds.',
        'harvested / ongoing',
        'P0',
        'candidate',
        'not_applicable',
        'needs_review',
        DATE '2026-07-03',
        'Can find agency data.json feeds and detect stale or broken source metadata.',
        jsonb_build_object(
            'inventory_file', 'us_government_api_seed_inventory_repo_status',
            'inventory_status', 'Verified public docs',
            'repo_usage_status', 'New candidate / not currently wired',
            'repo_next_action', 'Evaluate for fit, auth, quota, schema, and official-source provenance before adding an extractor.',
            'source_url', 'https://resources.data.gov/harvester-api/'
        )
    ),
    (
        'dcat-us-agency-data-json',
        'Project Open Data / DCAT-US agency data.json feeds',
        'Office of Management and Budget / GSA',
        'Project Open Data / Data.gov',
        'executive',
        'source_discovery',
        'feed',
        'open',
        'none',
        NULL,
        'https://www.agency.gov/data.json',
        'https://resources.data.gov/resources/dcat-us/',
        ARRAY['json', 'dcat-us']::text[],
        'Agency dataset, data service, and distribution metadata.',
        'agency maintained',
        'P0',
        'candidate',
        'not_applicable',
        'needs_review',
        DATE '2026-07-03',
        'Crawler candidate for trying /data.json on federal agency domains.',
        jsonb_build_object(
            'inventory_file', 'us_government_api_seed_inventory_repo_status',
            'inventory_status', 'Verified public docs',
            'repo_usage_status', 'New candidate / not currently wired',
            'repo_next_action', 'Evaluate for fit, auth, quota, schema, and official-source provenance before adding an extractor.',
            'source_url', 'https://resources.data.gov/resources/dcat-us3/'
        )
    ),
    (
        'gsa-open-api-directory',
        'GSA Open Technology API Directory',
        'General Services Administration',
        'Open Technology',
        'executive',
        'source_discovery',
        'directory',
        'open',
        'unknown',
        'varies',
        'https://open.gsa.gov/api/',
        'https://open.gsa.gov/api/',
        ARRAY['html', 'linked_docs']::text[],
        'GSA, SAM.gov, Data.gov, Regulations.gov, and other GSA/open government APIs.',
        'periodic',
        'P0',
        'candidate',
        'not_applicable',
        'needs_review',
        DATE '2026-07-03',
        'Seed directory for procurement, regulations, and government-wide service APIs; access varies by linked API.',
        jsonb_build_object(
            'inventory_file', 'us_government_api_seed_inventory_repo_status',
            'inventory_status', 'Verified public docs',
            'repo_usage_status', 'New candidate / not currently wired',
            'repo_next_action', 'Evaluate for fit, auth, quota, schema, and official-source provenance before adding an extractor.',
            'source_url', 'https://open.gsa.gov/api/'
        )
    ),
    (
        'congress-gov-api',
        'Congress.gov API v3',
        'Library of Congress',
        'Congress.gov',
        'legislative',
        'legislation',
        'api',
        'free_key',
        'api_key',
        'api.data.gov',
        'https://api.data.gov/congress/v3/',
        'https://www.loc.gov/apis/additional-apis/congress-dot-gov-api/',
        ARRAY['json', 'xml']::text[],
        'Bills, amendments, summaries, members, committees, nominations, treaties, Congressional Record, and related collections.',
        'ongoing / Congress.gov',
        'P0',
        'candidate',
        'verified',
        'needs_review',
        DATE '2026-07-03',
        'Official replacement or complement for GovTrack bill/member data; not wired yet.',
        jsonb_build_object(
            'inventory_file', 'us_government_api_seed_inventory_repo_status',
            'inventory_status', 'Verified public docs',
            'repo_usage_status', 'Not wired; official replacement/addition candidate',
            'repo_evidence', 'Current repo gets active members from @unitedstates/congress-legislators YAML, not Congress.gov API.',
            'repo_next_action', 'Consider for official bills, amendments, nominations, committee data, and legislative metadata.',
            'source_url', 'https://www.loc.gov/apis/additional-apis/congress-dot-gov-api/'
        )
    ),
    (
        'govinfo-api',
        'GovInfo API',
        'Government Publishing Office',
        'GovInfo',
        'legislative',
        'official_publications',
        'api',
        'free_key',
        'api_key',
        'api.data.gov',
        'https://api.govinfo.gov/',
        'https://www.govinfo.gov/developers',
        ARRAY['json', 'xml', 'mods', 'pdf', 'txt']::text[],
        'Official publications from all three branches, packages, granules, metadata, and bulk repositories.',
        'ongoing',
        'P0',
        'candidate',
        'verified',
        'needs_review',
        DATE '2026-07-03',
        'High-value official source for bill text, congressional documents, Congressional Record, regulations, and public laws.',
        jsonb_build_object(
            'inventory_file', 'us_government_api_seed_inventory_repo_status',
            'inventory_status', 'Verified public docs',
            'repo_usage_status', 'Not wired; high-value official candidate',
            'repo_evidence', 'No current extractor found in scraper/main.py or scraper/extractors for GovInfo.',
            'repo_next_action', 'Use package/granule IDs as immutable source identifiers; cross-link to Congress.gov and Federal Register.',
            'source_url', 'https://www.govinfo.gov/developers'
        )
    ),
    (
        'house-clerk-roll-call-xml',
        'House Clerk roll-call vote XML',
        'U.S. House of Representatives',
        'Office of the Clerk',
        'legislative',
        'votes',
        'feed',
        'open',
        'none',
        NULL,
        'https://clerk.house.gov/evs/',
        'https://clerk.house.gov/Votes',
        ARRAY['xml', 'html']::text[],
        'House roll-call votes, vote totals, and member-level positions.',
        'vote-driven',
        'P0',
        'candidate',
        'verified',
        'needs_review',
        DATE '2026-07-03',
        'Official House vote source candidate or reconciliation source for GovTrack-derived votes.',
        jsonb_build_object(
            'inventory_file', 'us_government_api_seed_inventory_repo_status',
            'inventory_status', 'Verified public source',
            'repo_usage_status', 'Not wired; official replacement/addition candidate',
            'repo_evidence', 'Current repo gets federal roll-call votes from GovTrack, not House Clerk XML.',
            'repo_next_action', 'Use as official House roll-call source or reconciliation source for GovTrack-derived votes.',
            'source_url', 'https://clerk.house.gov/Votes'
        )
    ),
    (
        'senate-roll-call-xml',
        'Senate roll-call vote XML',
        'United States Senate',
        'Senate Legislative Information System',
        'legislative',
        'votes',
        'feed',
        'open',
        'none',
        NULL,
        'https://www.senate.gov/legislative/LIS/roll_call_votes/',
        'https://www.senate.gov/legislative/votes_new.htm',
        ARRAY['xml', 'html']::text[],
        'Senate roll-call votes and member-level positions.',
        'vote-driven',
        'P0',
        'candidate',
        'verified',
        'needs_review',
        DATE '2026-07-03',
        'Official Senate vote source candidate or reconciliation source for GovTrack-derived votes.',
        jsonb_build_object(
            'inventory_file', 'us_government_api_seed_inventory_repo_status',
            'inventory_status', 'Verified public source',
            'repo_usage_status', 'Not wired; official replacement/addition candidate',
            'repo_evidence', 'Current repo gets federal roll-call votes from GovTrack, not Senate XML.',
            'repo_next_action', 'Use as official Senate roll-call source or reconciliation source for GovTrack-derived votes.',
            'source_url', 'https://www.senate.gov/legislative/votes_new.htm'
        )
    )
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    agency = EXCLUDED.agency,
    sub_agency = EXCLUDED.sub_agency,
    branch = EXCLUDED.branch,
    category = EXCLUDED.category,
    source_type = EXCLUDED.source_type,
    access_level = EXCLUDED.access_level,
    auth_type = EXCLUDED.auth_type,
    credential_provider = EXCLUDED.credential_provider,
    base_url = EXCLUDED.base_url,
    docs_url = EXCLUDED.docs_url,
    formats = EXCLUDED.formats,
    coverage = EXCLUDED.coverage,
    update_cadence = EXCLUDED.update_cadence,
    priority = EXCLUDED.priority,
    status = EXCLUDED.status,
    verified_lane = EXCLUDED.verified_lane,
    repo_fit = EXCLUDED.repo_fit,
    verified_at = EXCLUDED.verified_at,
    notes = EXCLUDED.notes,
    metadata = public.source_catalog_sources.metadata || EXCLUDED.metadata;

INSERT INTO public.source_catalog_endpoints (
    source_slug,
    endpoint_slug,
    display_name,
    endpoint_type,
    url,
    docs_url,
    formats,
    access_level,
    auth_type,
    credential_provider,
    update_cadence,
    status,
    notes,
    metadata
) VALUES
    ('api-data-gov', 'gateway-docs', 'api.data.gov gateway docs', 'directory', 'https://api.data.gov/', 'https://api.data.gov/', ARRAY['html']::text[], 'open', 'api_key', 'api.data.gov', 'continuous', 'candidate', 'Credential gateway docs for participating official APIs.', jsonb_build_object('inventory_file', 'us_government_api_seed_inventory_repo_status')),
    ('datagov-catalog-api-v4', 'catalog-api-v4', 'Data.gov Catalog API v4', 'api', 'https://api.gsa.gov/technology/datagov/v4/', 'https://resources.data.gov/catalog-api/', ARRAY['json']::text[], 'free_key', 'api_key', 'api.data.gov', 'harvested / ongoing', 'candidate', 'Source-discovery API for dataset and distribution metadata.', jsonb_build_object('inventory_file', 'us_government_api_seed_inventory_repo_status')),
    ('datagov-harvester-api', 'harvester-api-v2', 'Data.gov Harvester API v2', 'api', 'https://api.gsa.gov/technology/datagov_harvest/v2/', 'https://resources.data.gov/harvester-api/', ARRAY['json', 'openapi']::text[], 'free_key', 'api_key', 'api.data.gov / open.gsa.gov', 'harvested / ongoing', 'candidate', 'Harvest source and error metadata for agency feeds.', jsonb_build_object('inventory_file', 'us_government_api_seed_inventory_repo_status')),
    ('dcat-us-agency-data-json', 'agency-data-json-pattern', 'Agency /data.json feed pattern', 'feed', 'https://www.agency.gov/data.json', 'https://resources.data.gov/resources/dcat-us/', ARRAY['json', 'dcat-us']::text[], 'open', 'none', NULL, 'agency maintained', 'candidate', 'Pattern endpoint; actual agency URLs must be reviewed individually.', jsonb_build_object('inventory_file', 'us_government_api_seed_inventory_repo_status')),
    ('gsa-open-api-directory', 'api-directory', 'GSA Open Technology API Directory', 'directory', 'https://open.gsa.gov/api/', 'https://open.gsa.gov/api/', ARRAY['html', 'linked_docs']::text[], 'open', 'unknown', 'varies', 'periodic', 'candidate', 'Directory page for GSA/open government APIs; linked APIs need separate access review.', jsonb_build_object('inventory_file', 'us_government_api_seed_inventory_repo_status')),
    ('congress-gov-api', 'api-v3', 'Congress.gov API v3', 'api', 'https://api.data.gov/congress/v3/', 'https://www.loc.gov/apis/additional-apis/congress-dot-gov-api/', ARRAY['json', 'xml']::text[], 'free_key', 'api_key', 'api.data.gov', 'ongoing / Congress.gov', 'candidate', 'Official legislative metadata API candidate.', jsonb_build_object('inventory_file', 'us_government_api_seed_inventory_repo_status')),
    ('govinfo-api', 'api', 'GovInfo API', 'api', 'https://api.govinfo.gov/', 'https://www.govinfo.gov/developers', ARRAY['json', 'xml', 'mods', 'pdf', 'txt']::text[], 'free_key', 'api_key', 'api.data.gov', 'ongoing', 'candidate', 'Official publications API candidate.', jsonb_build_object('inventory_file', 'us_government_api_seed_inventory_repo_status')),
    ('house-clerk-roll-call-xml', 'evs-roll-call-feed', 'House Clerk roll-call vote XML', 'feed', 'https://clerk.house.gov/evs/', 'https://clerk.house.gov/Votes', ARRAY['xml', 'html']::text[], 'open', 'none', NULL, 'vote-driven', 'candidate', 'Official House vote feed candidate.', jsonb_build_object('inventory_file', 'us_government_api_seed_inventory_repo_status')),
    ('senate-roll-call-xml', 'lis-roll-call-feed', 'Senate roll-call vote XML', 'feed', 'https://www.senate.gov/legislative/LIS/roll_call_votes/', 'https://www.senate.gov/legislative/votes_new.htm', ARRAY['xml', 'html']::text[], 'open', 'none', NULL, 'vote-driven', 'candidate', 'Official Senate vote feed candidate.', jsonb_build_object('inventory_file', 'us_government_api_seed_inventory_repo_status'))
ON CONFLICT (source_slug, endpoint_slug) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    endpoint_type = EXCLUDED.endpoint_type,
    url = EXCLUDED.url,
    docs_url = EXCLUDED.docs_url,
    formats = EXCLUDED.formats,
    access_level = EXCLUDED.access_level,
    auth_type = EXCLUDED.auth_type,
    credential_provider = EXCLUDED.credential_provider,
    update_cadence = EXCLUDED.update_cadence,
    status = EXCLUDED.status,
    notes = EXCLUDED.notes,
    metadata = public.source_catalog_endpoints.metadata || EXCLUDED.metadata;

WITH review_seed(source_slug, reason, evidence) AS (
    VALUES
        ('api-data-gov', 'Seeded from July 2026 source inventory for credential-provider review.', jsonb_build_object('migration', '0017_source_inventory_p0_seed', 'inventory_file', 'us_government_api_seed_inventory_repo_status')),
        ('datagov-catalog-api-v4', 'Seeded from July 2026 source inventory for source-discovery review.', jsonb_build_object('migration', '0017_source_inventory_p0_seed', 'inventory_file', 'us_government_api_seed_inventory_repo_status')),
        ('datagov-harvester-api', 'Seeded from July 2026 source inventory for source-discovery review.', jsonb_build_object('migration', '0017_source_inventory_p0_seed', 'inventory_file', 'us_government_api_seed_inventory_repo_status')),
        ('dcat-us-agency-data-json', 'Seeded from July 2026 source inventory for source-discovery review.', jsonb_build_object('migration', '0017_source_inventory_p0_seed', 'inventory_file', 'us_government_api_seed_inventory_repo_status')),
        ('gsa-open-api-directory', 'Seeded from July 2026 source inventory for source-discovery review.', jsonb_build_object('migration', '0017_source_inventory_p0_seed', 'inventory_file', 'us_government_api_seed_inventory_repo_status')),
        ('congress-gov-api', 'Seeded from July 2026 source inventory for official legislative-source review.', jsonb_build_object('migration', '0017_source_inventory_p0_seed', 'inventory_file', 'us_government_api_seed_inventory_repo_status')),
        ('govinfo-api', 'Seeded from July 2026 source inventory for official publication-source review.', jsonb_build_object('migration', '0017_source_inventory_p0_seed', 'inventory_file', 'us_government_api_seed_inventory_repo_status')),
        ('house-clerk-roll-call-xml', 'Seeded from July 2026 source inventory for official vote-source review.', jsonb_build_object('migration', '0017_source_inventory_p0_seed', 'inventory_file', 'us_government_api_seed_inventory_repo_status')),
        ('senate-roll-call-xml', 'Seeded from July 2026 source inventory for official vote-source review.', jsonb_build_object('migration', '0017_source_inventory_p0_seed', 'inventory_file', 'us_government_api_seed_inventory_repo_status'))
)
INSERT INTO public.source_catalog_review_events (
    source_slug,
    previous_status,
    new_status,
    reviewer,
    reason,
    evidence
)
SELECT
    review_seed.source_slug,
    NULL,
    'candidate',
    'source-inventory-2026-07',
    review_seed.reason,
    review_seed.evidence
FROM review_seed
WHERE NOT EXISTS (
    SELECT 1
    FROM public.source_catalog_review_events AS existing
    WHERE existing.source_slug = review_seed.source_slug
      AND existing.endpoint_slug IS NULL
      AND existing.new_status = 'candidate'
      AND existing.reason = review_seed.reason
);

NOTIFY pgrst, 'reload schema';
