"""initial schema

Revision ID: a7b4496a01ea
Revises: None
Create Date: 2026-06-08 13:04:26.218758
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a7b4496a01ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contribution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('donor_name', sa.String(length=300), nullable=False),
    sa.Column('donor_type', sa.String(length=50), nullable=False),
    sa.Column('recipient_name', sa.String(length=300), nullable=False),
    sa.Column('committee_id', sa.String(length=20), nullable=True),
    sa.Column('politician_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('election_cycle', sa.Integer(), nullable=True),
    sa.Column('fec_filing_id', sa.String(length=50), nullable=True),
    sa.Column('amendment_indicator', sa.String(length=5), nullable=True),
    sa.Column('employer', sa.String(length=300), nullable=True),
    sa.Column('occupation', sa.String(length=300), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['politician_id'], ['politician.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'source_record_id', name='uq_contribution_dedup')
    )
    op.create_table('government_contract',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('award_id', sa.String(length=100), nullable=False),
    sa.Column('recipient_name', sa.String(length=500), nullable=False),
    sa.Column('awarding_agency', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('award_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('naics_code', sa.String(length=10), nullable=True),
    sa.Column('place_of_performance', sa.String(length=500), nullable=True),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'source_record_id', name='uq_contract_dedup')
    )
    op.create_table('lobbying_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lda_id', sa.String(length=50), nullable=False),
    sa.Column('registrant_name', sa.String(length=500), nullable=False),
    sa.Column('client_name', sa.String(length=500), nullable=True),
    sa.Column('lobbyist_name', sa.String(length=500), nullable=True),
    sa.Column('issue_area', sa.String(length=200), nullable=True),
    sa.Column('issue_text', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('report_quarter', sa.String(length=10), nullable=True),
    sa.Column('filing_type', sa.String(length=30), nullable=True),
    sa.Column('government_entities_lobbied', sa.Text(), nullable=True),
    sa.Column('source_xml_url', sa.String(length=1000), nullable=True),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'source_record_id', name='uq_lobbying_dedup')
    )
    op.create_table('organization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('fec_id', sa.String(length=20), nullable=True),
    sa.Column('opensecrets_id', sa.String(length=20), nullable=True),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'source_record_id', name='uq_organization_dedup')
    )
    op.create_table('politician',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('suffix', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=300), nullable=False),
    sa.Column('party_history', sa.JSON(), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('district', sa.String(length=10), nullable=True),
    sa.Column('chamber', sa.String(length=20), nullable=False),
    sa.Column('bioguide_id', sa.String(length=20), nullable=True),
    sa.Column('fec_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('lis_id', sa.String(length=20), nullable=True),
    sa.Column('icpsr_id', sa.String(length=20), nullable=True),
    sa.Column('voteview_id', sa.String(length=20), nullable=True),
    sa.Column('govtrack_id', sa.String(length=20), nullable=True),
    sa.Column('opensecrets_id', sa.String(length=20), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('bio_text', sa.String(), nullable=True),
    sa.Column('in_office', sa.Boolean(), nullable=False),
    sa.Column('term_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('term_end', sa.ARRAY(sa.DateTime(timezone=True)), nullable=True),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_data_refresh', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'source_record_id', name='uq_politician_dedup')
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_interval', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('errors', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_admin_only', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('financial_disclosure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('filing_year', sa.Integer(), nullable=True),
    sa.Column('filing_type', sa.String(length=50), nullable=True),
    sa.Column('asset_name', sa.String(length=500), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=True),
    sa.Column('amount_range_low', sa.Float(), nullable=True),
    sa.Column('amount_range_high', sa.Float(), nullable=True),
    sa.Column('notification_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['politician_id'], ['politician.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'source_record_id', name='uq_financial_dedup')
    )
    op.create_table('politician_contribution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('contribution_id', sa.Integer(), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('match_method', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['contribution_id'], ['contribution.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['politician_id'], ['politician.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('politician_id', 'contribution_id', name='uq_politician_contribution')
    )
    op.create_table('politician_government_contract',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('match_method', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['government_contract.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['politician_id'], ['politician.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('politician_id', 'contract_id', name='uq_politician_contract')
    )
    op.create_table('politician_ideology_score',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('congress', sa.Integer(), nullable=False),
    sa.Column('chamber', sa.String(length=20), nullable=False),
    sa.Column('dw_nominate_dim1', sa.Float(), nullable=True),
    sa.Column('dw_nominate_dim2', sa.Float(), nullable=True),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['politician_id'], ['politician.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'source_record_id', name='uq_ideology_score_dedup')
    )
    op.create_table('politician_lobbying_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('lobbying_record_id', sa.Integer(), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('match_method', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['lobbying_record_id'], ['lobbying_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['politician_id'], ['politician.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('politician_id', 'lobbying_record_id', name='uq_politician_lobbying')
    )
    op.create_table('voting_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('roll_call_number', sa.Integer(), nullable=False),
    sa.Column('congress', sa.Integer(), nullable=False),
    sa.Column('session', sa.Integer(), nullable=False),
    sa.Column('chamber', sa.String(length=20), nullable=False),
    sa.Column('bill_id', sa.String(length=50), nullable=True),
    sa.Column('bill_title', sa.String(length=1000), nullable=True),
    sa.Column('bill_type', sa.String(length=20), nullable=True),
    sa.Column('bill_number', sa.String(length=20), nullable=True),
    sa.Column('vote', sa.String(length=20), nullable=False),
    sa.Column('vote_date', sa.Date(), nullable=True),
    sa.Column('issue_area', sa.String(length=200), nullable=True),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['politician_id'], ['politician.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'source_record_id', name='uq_voting_record_dedup')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voting_record')
    op.drop_table('politician_lobbying_record')
    op.drop_table('politician_ideology_score')
    op.drop_table('politician_government_contract')
    op.drop_table('politician_contribution')
    op.drop_table('financial_disclosure')
    op.drop_table('tag')
    op.drop_table('source')
    op.drop_table('politician')
    op.drop_table('organization')
    op.drop_table('lobbying_record')
    op.drop_table('government_contract')
    op.drop_table('contribution')
    # ### end Alembic commands ###
